{
    "name": "Theme KDMobilier",
    "version": "1.0",
    "author": "Hotcodes",
    "category": "Theme/Ecommerce",
    "description": "This is the first theme for kdmobilier",
    "depends": [
        "website",
        "website_blog",
        "website_sale",
        "website_sale_wishlist",
        "website_helpdesk",
        "website_mass_mailing",
    ],
    "data": [
        "views/layout.xml",
        "views/header_template.xml",
        "views/footer_template.xml",
        "views/kdmobilier_homepage.xml",
        "views/kdmobilier_templates.xml",
        "views/blog_templates.xml",
        "views/menues.xml",
        "views/contact_us.xml",
        "views/auth_templage.xml",
        "views/services.xml",
        "views/design-planning.xml",
        "views/entretien-canape.xml",
        "views/conseil-decoration.xml",
        # "views/aboutus_page.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            # GOOGLE FONTS
            "https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap",
            "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap",
            # Development assets
            "/theme_kdmobilier/static/src/js/dev_mode.js",
            # Production assets
            # CSS
            # "/theme_kdmobilier/static/src/css/main.css",
            # "/theme_kdmobilier/static/build/css/styles.css",
            # "/theme_kdmobilier/static/src/css/custom.css",
            # CSS
            # "theme_kdmobilier/static/src/css/aos.css",
            # "theme_kdmobilier/static/src/css/flaticon.css",
            # "theme_kdmobilier/static/src/css/fontawesome.css",
            # "theme_kdmobilier/static/src/css/magnific-popup.css",
            # "theme_kdmobilier/static/src/css/pbminfotech-base-icons.css",
            # "theme_kdmobilier/static/src/css/shortcode.css",
            "theme_kdmobilier/static/src/css/swiper.min.css",
            # "theme_kdmobilier/static/src/css/themify-icons.css",
            # "theme_kdmobilier/static/src/css/twentytwenty.css",
            "theme_kdmobilier/static/src/css/base.css",
            "theme_kdmobilier/static/src/css/responsive.css",
            # "theme_kdmobilier/static/src/css/bootstrap.min.css",
            "theme_kdmobilier/static/src/scss/_fonts.scss",
            "theme_kdmobilier/static/src/css/style.css",
            # JAVA SCRIPT
            "/theme_kdmobilier/static/build/js/main.js",
            "theme_kdmobilier/static/src/js/attributes.js",
            "theme_kdmobilier/static/src/js/poppup.js",
            "theme_kdmobilier/static/src/js/maps.js",
            "theme_kdmobilier/static/src/js/infinite_scroll.js",
            # "theme_kdmobilier/static/src/js/jquery.min.js",
            # "theme_kdmobilier/static/src/js/popper.min.js",
            # "theme_kdmobilier/static/src/js/bootstrap.min.js",
            # "theme_kdmobilier/static/src/js/jquery.waypoints.min.js",
            # "theme_kdmobilier/static/src/js/jquery.magnific-popup.min.js",
            # "theme_kdmobilier/static/src/js/jquery.appear.js",
            "theme_kdmobilier/static/src/js/swiper.min.js",
            # "theme_kdmobilier/static/src/js/circle-progress.min.js",
            # "theme_kdmobilier/static/src/js/isotope.pkgd.min.js",
            # "theme_kdmobilier/static/src/js/jquery.countdown.min.js",
            # "/theme_kdmobilier/static/src/js/aos.js",
            # "theme_kdmobilier/static/src/js/gsap.js",
            # "theme_kdmobilier/static/src/js/masonry.min.js",
            # "theme_kdmobilier/static/src/js/numinate.min.js",
            # "theme_kdmobilier/static/src/js/ScrollTrigger.js",
            # "theme_kdmobilier/static/src/js/SplitText.js",
            # "theme_kdmobilier/static/src/js/magnetic.js",
            # "theme_kdmobilier/static/src/js/morphext.min.js",
            # "theme_kdmobilier/static/src/js/gsap-animation.js",
            # "theme_kdmobilier/static/src/js/jquery.event.move.js",
            # "theme_kdmobilier/static/src/js/jquery.twentytwenty.js",
            # "theme_kdmobilier/static/src/js/jquery-validate/jquery.validate.min.js",
            # "theme_kdmobilier/static/src/js/scripts.js",
            "theme_kdmobilier/static/src/js/salon_products.js",
            "theme_kdmobilier/static/src/js/wishlist.js",
            "theme_kdmobilier/static/src/js/dropdown_extension.js",
        ],
        "web.assets_primary_variables": [
            ("prepend", "theme_kdmobilier/static/src/scss/primary_variables.scss"),
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
